### PR TITLE
Another Python3 Port (YAPP?)

### PR DESCRIPTION
**Pull request by ianamason**
Pretty straightforward in retrospect.

### CODE REVIEW

**Comment by dddejan** [comment]
Looks good but I am having trouble checking python3 version. Travis is running checks on python2 and I don't know how to tell Cmake to use python3 on my computer. Any ideas @ianamason ?

**Comment by ianamason** [comment]
What sort of computer is it?  Does it come with whistles and bells?

**Comment by dddejan** [comment]
> What sort of computer is it? Does it come with whistles and bells?

Just regular CSL mac with brew.

**Comment by ianamason** [comment]
Brew install python 

Should give you 3

**Comment by ianamason** [comment]
I pulled in your magic, and it didn't break anything (but it already worked out of the box).

**Comment by dddejan** [comment]
There are also examples in the `examples` directory that don't currently run with python3

```
python3 cad.py
Traceback (most recent call last):
  File "cad.py", line 96, in <module>
    cad(polys, vars)
  File "cad.py", line 89, in cad
    lift(poly_map, vars) 
  File "cad.py", line 81, in lift
    lift_first_var(poly_map, vars, m)
  File "cad.py", line 66, in lift_first_var
    for r1, r2 in itertools.izip(r_i, r_j):
AttributeError: module 'itertools' has no attribute 'izip'
```

**Comment by ianamason** [comment]
I will fix after pool.

**Comment by ianamason** [comment]
Right.  I did some scratching around.  Seems doable for the [linux bit](https://stackoverflow.com/questions/30496189/how-to-use-python-3-as-a-build-script-in-non-python-travis-configuration), but I am not sure about the osx side of things.

**Comment by ianamason** [comment]
On a related note, I looked around for similar Frankenstein C-python projects and found [this](https://martinopilia.com/posts/2018/09/15/building-python-extension.html), which refereed to [this](https://github.com/m-pilia/disptools/blob/master/.appveyor.yml) which uses appveyor.

The short coming with this current pull, apart from the continuous integration stuff, is that there is no standard way to install the python module.

**Comment by ianamason** [comment]
[BUT](https://help.appveyor.com/discussions/questions/34614-macos-roadmap)

**Comment by dddejan** [comment]
I found (this)[https://github.com/praekeltfoundation/travis-pyenv/blob/develop/README.md] and have seen people mention to use pyenv, whatever that is

**Comment by ianamason** [comment]
[It](https://github.com/pyenv/pyenv) also uses travis to check itself, so that is encouraging.

**Comment by ianamason** [comment]
Put a fork in it Dejan. It's [done](https://travis-ci.org/SRI-CSL/libpoly/builds/593230406)

Travis checks take a long time (mainly because on OS X  two versions of python need to be built).

We could halve this, by only checking the Release build.

**Pull request merged**
